create table if not exists ovc.ovc_run_reports_v01 (
  run_id              text primary key,          -- generated by worker/job (uuid or timestamped id)
  run_type            text not null check (run_type in ('INGEST_MIN','BACKFILL_MIN','OUTCOMES')),
  env                 text not null check (env in ('staging','prod')),
  started_at          timestamptz not null,
  finished_at         timestamptz not null,

  -- counts
  input_count         integer not null,
  raw_written_count   integer not null,
  parse_ok_count      integer not null,
  parse_fail_count    integer not null,
  upsert_inserted     integer not null,
  upsert_updated      integer not null,

  -- versions observed
  contract_ver        text not null,
  worker_ver          text null,
  sql_ver             text null,

  -- data quality rollups (fill what you can now; extend later)
  dq_ohlc_fail_count   integer not null default 0,
  dq_rng_mismatch_count integer not null default 0,
  dq_dir_inconsistency_count integer not null default 0,

  verdict             text not null check (verdict in ('PASS','WARN','FAIL')),
  notes               text null
);

create index if not exists idx_ovc_run_reports_started on ovc.ovc_run_reports_v01(started_at desc);
